version: '3.1'
services:
  icorp-test:
    build:
      context: .
      dockerfile: Dockerfile-ms-icorp-test
    restart: always
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: person
      MONGODB_USER: admin
      MONGODB_PASSWORD: admin
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: icorp-network
