#!groovy

env.PATH_PROJECT='crud-demo/'

node {
	deleteDir()
	
	stage('Descargar fuentes') {
		checkout scm
	}
	
        stage('Pruebas unitarias') {
                script {
                    sh "cd ${PATH_PROJECT} && ./mvnw -f pom.xml test"
            	}
        }

       stage('Compilar aplicación') {
                script {
                	sh "cd ${PATH_PROJECT} && ./mvnw -f pom.xml package -DskipTests"
                }
        }
	
	stage('Desplegar aplicación') {
		script {
			sh "cd ${PATH_PROJECT} && /var/jenkins_home/docker-compose/docker-compose up -d docker-compose.yml"
		}
	}
}
