#!groovy

env.PATH_PROJECT='crud-demo/'

node {
	deleteDir()
	
	stage('Descargar fuentes') {
		checkout scm
	}
	
        stage('Pruebas unitarias') {
                script {
                    sh "cd ${PATH_PROJECT} && ./mvnw -f pom.xml test"
            	}
        }

       stage('Compilar aplicación') {
                script {
                	sh "cd ${PATH_PROJECT} && ./mvnw -f pom.xml package -DskipTests"
                }
        }
	
	stage('Desplegar aplicación') {
		agent {
			label 'ec2_node'
		}
		script {
			sh "cd ${PATH_PROJECT} && sudo /usr/local/bin/docker-compose up -d"
		}
	}
}
