spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: person
      port: 27017
      host: mongodb
    rest:
      base-path: '/cruddemo/v1'
